name: Automated release creation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 1"

jobs:
  release_management:
    uses: newrelic/coreint-automation/.github/workflows/reusable_release_automation.yaml@v4
    secrets: inherit
